mybatis-plus:
  global-config:
    db-column-underline: true
#   对应service下日子
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
